#!/bin/bash


# Correr script desde el root path del repo de terraform

# Inputs:
#   - Nombre de la lambda
#   - Booleano indicando si tiene configs

# En TERRAFORM
# Lambda:
#   - Copiar archivo scripts/templates/lambda_terraform_template.tf a lambda/NombreDeLaLambda/main.tf
#   - Copiar archivo scripts/templates/lambda_policy_template.tpl a lambda/NombreDeLaLambda/policies/main.tf
#   - Correr script de symlinks/variables/outputs
# Configs:
#   - Si tiene configs, copiar scripts/templates/configs_terraform_template.tf a configs/NombreDeLaLambda/main.tf
#   - Correr script de symlinks/variables/outputs

# En TERRAGRUNT
# Ubicarse en la carpeta root del repo de terragrunt
# Lambda:
#   - Copiar archivo scripts/templates/lambda_terragrunt_template.hcl a dev/lambda/NombreDeLaLambda/terragrunt.hcl
# Configs:
#   - Si tiene configs, copiar archivo scripts/templates/configs_terragrunt_template.hcl a dev/lambda/NombreDeLaLambda/terragrunt.hcl


clear

echo -n "Enter new lambda name: "
read LAMBDA_NAME


####################################################
# Templates variables
templatesPath="../terragen/templates"

lambdaTerraformTemplate="${templatesPath}/lambda_terraform_template.tf"
configsTerraformTemplate="${templatesPath}/configs_terraform_template.tf"
lambdaPolicyTemplate="${templatesPath}/lambda_policy_template.tpl"

lambdaTerragruntTemplate="${templatesPath}/lambda_terragrunt_template.hcl"
configsTerragruntTemplate="${templatesPath}/configs_terragrunt_template.hcl"

####################################################
# Terraform
terraformPath="${PWD##*/}"

lambdaTerraformPath="lambda/${LAMBDA_NAME}"
lambdaPoliciesPath="${lambdaTerraformPath}/policies"
configsTerraformPath="configs/${LAMBDA_NAME}"

####################################################
# Terraform variables
terragruntPath="../${terraformPath}-live"

lambdaTerragruntPath="dev/lambda/${LAMBDA_NAME}"
configsTerragruntPath="dev/configs/${LAMBDA_NAME}"



###################################################################################################################
# TERRAFORM
# Lambda:
#   - Copiar archivo scripts/templates/lambda_terraform_template.tf a lambda/NombreDeLaLambda/main.tf
mkdir -p -v $lambdaTerraformPath
cp $lambdaTerraformTemplate "${lambdaTerraformPath}/main.tf"
#   - Copiar archivo scripts/templates/lambda_policy_template.tpl a lambda/NombreDeLaLambda/policies/main.tf
mkdir -p -v $lambdaPoliciesPath
cp $lambdaPolicyTemplate "${lambdaPoliciesPath}/policy.tpl"
#   - Correr script de symlinks/variables/outputs
ln -s commons.tf "${lambdaTerraformPath}/commons.tf"
ln -s lambda/global_variables.tf "${lambdaTerraformPath}/global_variables.tf"
touch "${lambdaTerraformPath}/variables.tf"
touch "${lambdaTerraformPath}/outputs.tf"

# Configs:
#   - Si tiene configs, copiar scripts/templates/configs_terraform_template.tf a configs/NombreDeLaLambda/main.tf
mkdir -p -v $configsTerraformPath
cp $configsTerraformTemplate "${configsTerraformPath}/main.tf"
#   - Correr script de symlinks/variables/outputs
ln -s -v commons.tf "${configsTerraformPath}/commons.tf"
ln -s -v configs/global_variables.tf "${configsTerraformPath}/global_variables.tf"
touch "${configsTerraformPath}/variables.tf"

# Add to git commit
git add $lambdaTerraformPath
git add $configsTerraformPath


###################################################################################################################
# TERRAGRUNT
# Ubicarse en la carpeta root del repo de terragrunt
cd $terragruntPath
# Lambda:
#   - Copiar archivo scripts/templates/lambda_terragrunt_template.hcl a dev/lambda/NombreDeLaLambda/terragrunt.hcl
mkdir -p -v $lambdaTerragruntPath
cp $lambdaTerragruntTemplate "${lambdaTerragruntPath}/terragrunt.hcl"
# Configs:
#   - Si tiene configs, copiar archivo scripts/templates/configs_terragrunt_template.hcl a dev/lambda/NombreDeLaLambda/terragrunt.hcl
mkdir -p -v $configsTerragruntPath
cp $configsTerragruntTemplate "${configsTerragruntPath}/terragrunt.hcl"

# Add to git commit
git add $lambdaTerragruntPath
git add $configsTerragruntPath
