#!/bin/bash

# Correr script desde el root path del repo de terraform

# Inputs:
#   - Nombre de la lambda
#   - Booleano indicando si tiene configs

# En TERRAFORM
# Lambda:
#   - Copiar archivo scripts/templates/lambda_terraform_template.tf a lambda/NombreDeLaLambda/main.tf
#   - Copiar archivo scripts/templates/lambda_policy_template.tpl a lambda/NombreDeLaLambda/policies/main.tf
#   - Correr script de symlinks/variables/outputs
# Configs:
#   - Si tiene configs, copiar scripts/templates/configs_terraform_template.tf a configs/NombreDeLaLambda/main.tf
#   - Correr script de symlinks/variables/outputs

# En TERRAGRUNT
# Ubicarse en la carpeta root del repo de terragrunt
# Lambda:
#   - Copiar archivo scripts/templates/lambda_terragrunt_template.hcl a dev/lambda/NombreDeLaLambda/terragrunt.hcl
# Configs:
#   - Si tiene configs, copiar archivo scripts/templates/configs_terragrunt_template.hcl a dev/lambda/NombreDeLaLambda/terragrunt.hcl


clear

echo $ARTIFACT_ID

if [ $1 = "lambda" ]; then
    echo -n "Enter new lambda name: "
    read LAMBDA_NAME

    echo -n "Enter artifact id: "
    read ARTIFACT_ID


    ###################################################
    # Utils
    terraformBranch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
    snakeCaseLambdaName=$(echo $LAMBDA_NAME                                        \
                            | sed 's/\([^A-Z]\)\([A-Z0-9]\)/\1_\2/g'               \
                            | sed 's/\([A-Z0-9]\)\([A-Z0-9]\)\([^A-Z]\)/\1_\2\3/g' \
                            | tr '[:upper:]' '[:lower:]')
    kebabCaseLambdaName=$(echo $LAMBDA_NAME                                        \
                            | sed 's/\([^A-Z]\)\([A-Z0-9]\)/\1-\2/g'               \
                            | sed 's/\([A-Z0-9]\)\([A-Z0-9]\)\([^A-Z]\)/\1-\2\3/g' \
                            | tr '[:upper:]' '[:lower:]')


    if [ -z $ARTIFACT_ID ]; then
        ARTIFACT_ID=$(echo "${kebabCaseLambdaName}-aws-lambda" | sed s/"-service"//)
    fi

    ###################################################
    # Templates variables
    full_path=$(realpath $0)

    dir_path=$(dirname $full_path)
    templatesPath="${dir_path}/templates"
    #
    lambdaTerraformTemplate="${templatesPath}/lambda_terraform_template.tf"
    lambdaOutputsTemplate="${templatesPath}/lambda_outputs_template.tf"
    lambdaPolicyTemplate="${templatesPath}/lambda_policy_template.tpl"
    configsTerraformTemplate="${templatesPath}/configs_terraform_template.tf"
    configsVariablesTemplate="${templatesPath}/configs_variables_template.tf"
    #
    lambdaTerragruntTemplate="${templatesPath}/lambda_terragrunt_template.hcl"
    configsTerragruntTemplate="${templatesPath}/configs_terragrunt_template.hcl"

    ####################################################
    # Terraform Variables
    terraformPath="${PWD##*/}"
    #
    lambdaTerraformPath="lambda/${LAMBDA_NAME}"
    lambdaPoliciesPath="${lambdaTerraformPath}/policies"
    lambdaPolicyName=$(echo "iam_p_${snakeCaseLambdaName}.tpl" | sed s/"_service"//)
    configsTerraformPath="configs/${LAMBDA_NAME}"

    ####################################################
    # Terraform variables
    terragruntPath="../${terraformPath}-live"
    #
    lambdaTerragruntPath="dev/lambda/${LAMBDA_NAME}"
    configsTerragruntPath="dev/configs/${LAMBDA_NAME}"


    ###################################################################################################################
    # TERRAFORM
    # Lambda:
    #   - Copiar archivo scripts/templates/lambda_terraform_template.tf a lambda/NombreDeLaLambda/main.tf
    mkdir -p -v $lambdaTerraformPath
    cp $lambdaTerraformTemplate "${lambdaTerraformPath}/main.tf"
    #
    #   - Copiar archivo scripts/templates/lambda_policy_template.tpl a lambda/NombreDeLaLambda/policies/main.tf
    mkdir -p -v $lambdaPoliciesPath
    cp $lambdaPolicyTemplate "${lambdaPoliciesPath}/${lambdaPolicyName}"
    #
    #   - Correr script de symlinks/variables/outputs
    ln -s ../../commons.tf "${lambdaTerraformPath}/commons.tf"
    ln -s ../global_variables.tf "${lambdaTerraformPath}/global_variables.tf"
    cp $lambdaOutputsTemplate "${lambdaTerraformPath}/outputs.tf"
    touch "${lambdaTerraformPath}/variables.tf"
    #
    # Configs:
    #   - Si tiene configs, copiar scripts/templates/configs_terraform_template.tf a configs/NombreDeLaLambda/main.tf
    mkdir -p -v $configsTerraformPath
    cp $configsTerraformTemplate "${configsTerraformPath}/main.tf"
    #
    #   - Correr script de symlinks/variables/outputs
    ln -s -v ../../commons.tf "${configsTerraformPath}/commons.tf"
    ln -s -v ../global_variables.tf "${configsTerraformPath}/global_variables.tf"
    cp $configsVariablesTemplate "${configsTerraformPath}/variables.tf"
    #
    # Replace names in files
    find $lambdaTerraformPath -type f -print0 | xargs -0 sed -i "" -e "s/lambda_name_service/${snakeCaseLambdaName}/g" 2> /dev/null
    find $lambdaTerraformPath -type f -print0 | xargs -0 sed -i "" -e "s/LambdaNameService/${LAMBDA_NAME}/g" 2> /dev/null
    find $lambdaTerraformPath -type f -print0 | xargs -0 sed -i "" -e "s/artifactId/${ARTIFACT_ID}/g" 2> /dev/null
    find $lambdaTerraformPath -type f -print0 | xargs -0 sed -i "" -e "s/iam_p_lambda_name.tpl/${lambdaPolicyName}/g" 2> /dev/null
    find $configsTerraformPath -type f -print0 | xargs -0 sed -i "" -e "s/lambda_name_service/${snakeCaseLambdaName}/g" 2> /dev/null
    find $configsTerraformPath -type f -print0 | xargs -0 sed -i "" -e "s/LambdaNameService/${LAMBDA_NAME}/g" 2> /dev/null
    #
    # Add to git commit
    git add $lambdaTerraformPath
    git add $configsTerraformPath


    ###################################################################################################################
    # TERRAGRUNT
    # Ubicarse en la carpeta root del repo de terragrunt
    cd $terragruntPath
    #
    # Lambda:
    #   - Copiar archivo scripts/templates/lambda_terragrunt_template.hcl a dev/lambda/NombreDeLaLambda/terragrunt.hcl
    mkdir -p -v $lambdaTerragruntPath
    cp $lambdaTerragruntTemplate "${lambdaTerragruntPath}/terragrunt.hcl"
    #
    # Configs:
    #   - Si tiene configs, copiar archivo scripts/templates/configs_terragrunt_template.hcl a dev/lambda/NombreDeLaLambda/terragrunt.hcl
    mkdir -p -v $configsTerragruntPath
    cp $configsTerragruntTemplate "${configsTerragruntPath}/terragrunt.hcl"
    #
    # Replace names in files
    find $lambdaTerragruntPath -type f -print0 | xargs -0 sed -i "" -e "s/lambda_name_service/${snakeCaseLambdaName}/g" 2> /dev/null
    find $lambdaTerragruntPath -type f -print0 | xargs -0 sed -i "" -e "s/LambdaNameService/${LAMBDA_NAME}/g" 2> /dev/null
    find $lambdaTerragruntPath -type f -print0 | xargs -0 sed -i "" -e "s/terraform_branch/${terraformBranch}/g" 2> /dev/null
    find $configsTerragruntPath -type f -print0 | xargs -0 sed -i "" -e "s/lambda_name_service/${snakeCaseLambdaName}/g" 2> /dev/null
    find $configsTerragruntPath -type f -print0 | xargs -0 sed -i "" -e "s/LambdaNameService/${LAMBDA_NAME}/g" 2> /dev/null
    find $configsTerragruntPath -type f -print0 | xargs -0 sed -i "" -e "s/terraform_branch/${terraformBranch}/g" 2> /dev/null
    #
    # Add to git commit
    git add $lambdaTerragruntPath
    git add $configsTerragruntPath

    echo "Lambda created successfully! :)"
else
    RED='\033[0;31m'
    NC='\033[0m'
    echo -e "Invalid option ${RED}[${1}]${NC} :("
    echo "Maybe you wanted to say:"
    echo "       terragen lambda"
fi
